#!/usr/bin/env bash
# declare an array variable
# bigger runs (for night)
#K_array=( 512 256 128 64 32 16 8 4 2 )
#           9  8    7   6  5  4 3 2 1
#D_array=( 1 2 3 4 5 6 7 8 9 10 11 12)

# smaller runs (for day) 
K_array=( 64 32 16 8 )
#         6   5  4  3
D_array=( 6 5 4 3 2 1 )


# get length of an array
K_length=${#K_array[@]}
D_length=${#D_array[@]}
id=0

#C=3
#H=64
#W=64
L=14
#input_bits=$(($C * $H * $W * 8))
input_bits=$(($L))

for (( d=0; d<D_length; d++ ));
do
    for (( k=0; k<K_length; k++ ));
    do
    id=$((id + 1)) 
    K="${K_array[$k]}"
    D="${D_array[$d]}"
    log2_K=$(awk -v a="$K" 'BEGIN{print log(a)/log(2)}')
    bits=$(($D * $log2_K))
    printf "$id) Running for K = $K & D = $D (i.e. bits = $bits)"
    python /home/novakovm/iris/MILOS/autoencoders.py $K $D $id
    printf "\n"
    printf "**************************************** \n"
    printf "\n"
    #printf "Current index %d with value %s\n" $j "${mahabharata[$j]}"
    done
done


# #echo "Running for K = 512 & D = 64 :"
# #python /home/novakovm/iris/MILOS/autoencoders.py 512 64 0

# #!/bin/bash
# # declare an array called array and define 3 vales

# # get length of an array
# length=${#array[@]}

# id=0

# for K in "${array[@]}"
# do
#     #id = $(( $id + 1 ))
#     id=$((id + 1)) 
#     echo 
#     python /home/novakovm/iris/MILOS/autoencoders.py $K 64 $id
# done