training_hyperparams:
- NUM_WORKERS: 4
- USE_PRETRAINED_MODEL: false
- USE_PRETRAINED_MODEL_run_id: 100
- USE_PRETRAINED_MODEL_current_time_str: '2023_01_19_16_24_47'
- USE_GPU: true
- NUM_EPOCHS: 520
- BATCH_SIZE_TRAIN: 128
- BATCH_SIZE_VAL: 128
- BATCH_SIZE_TEST: 1
- LEARNING_RATE: 200
- TRAIN_DATA_PATH: /home/novakovm/DATA_TRAIN/
- VAL_DATA_PATH: /home/novakovm/DATA_VALIDATE/
- TEST_DATA_PATH: /home/novakovm/DATA_TEST/
- TRAIN_IMAGES_MEAN_FILE_PATH: /home/novakovm/iris/MILOS/RGB_mean.npy
- TRAIN_IMAGES_STD_FILE_PATH: /home/novakovm/iris/MILOS/RGB_std.npy
- TRAIN_IMAGES_TOTAL_MEAN_FILE_PATH: /home/novakovm/iris/MILOS/train_dataset_mean.npy
- TRAIN_IMAGES_TOTAL_STD_FILE_PATH: /home/novakovm/iris/MILOS/train_dataset_std.npy
- H: 64
- W: 64
- C: 3
- MAX_TOTAL_IMAGE_NUMBER: 268435456
- TOTAL_NUMBER_OF_IMAGES: 100000
- TOTAL_NUMBER_OF_SHAPES: 2
- train_dataset_percentage: 75.0
- val_dataset_percentage: 12.5
- test_dataset_percentage: 12.5
- DATA_PATH: /home/novakovm/DATA/
- ROOT_PATH: /home/novakovm/iris/MILOS/
- data_generator_path: /home/novakovm/iris/MILOS/main.py
- LOGGER_PATH: /home/novakovm/iris/MILOS/log_all.txt
- SEED: 1
- model_name: VQ_VAE
- run_id: 108
- SET_VAR_TO_ONE: false
- requires_normalization_with_sphere_projection: true
- train_with_quantization: true
- PCA_decomp_in_every_epochs: false
- K: 128
- M: 1
- beta: 0.25
- use_EMA: false
- gamma: 0.99
- D: 16
- res_blocks_channel_number_in_hidden_layers: 32
- res_block_size: 2
- res_block_use_BN: true
- res_block_use_bias: true
- use_BN: false
- max_channel_number: 256
- divisor_value: 2
- GENERATE_DATA: false
- PREPROCESS_DATA: false
- INFERENCE_DATA: true
- RUN_MODEL_TESTING: true
- RUN_TRAIN_VAL_AVG_LOSS_OVER_EPOCHS: true
- RUN_SCATTER_FOR_SPECIFIC_CLASSES: false
- RUN_TOP_WORST_RECONSTRUCTED_TEST_IMAGES: false
- RUN_TOP_BEST_RECONSTRUCTED_TEST_IMAGES: false
- RUN_MODEL_VIZUALIZATION: false
- RUN_CODEBOOK_VISUALIZATION: false
- RUN_PCA_ON_CODEBOOK: false
- RUN_TOKEN_VIZUALIZATION: false
- SAVE_RESULTS_TO_CSV: true
- VISUALIZE_THE_CHANGE_OF_CODEBOOK_TOKENS: false
